"""Price and turnaround tables, generated from the shared catalogue (D-022; SPEC §10.4).

`configs/prices_inr.yaml` and `configs/turnaround.yaml` are written by
`sambhasha tables generate` and never edited by hand; a test fails if they drift from the
catalogue. Tests take their CGHS rate (or flagged estimate) and turnaround from the
catalogue; history, examination, bedside tests and consultant sessions take the SPEC's
defaults; a request outside the catalogue gets the median test price, flagged as estimated.
"""

import hashlib
import statistics
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Final

import yaml

from sambhasha.catalogue import (
    DEFAULT_CATALOGUE_DIR,
    PINNED_CATALOGUE_VERSION,
    Catalogue,
)

CONFIGS: Final = Path(__file__).resolve().parents[3] / "configs"
PRICES_PATH: Final = CONFIGS / "prices_inr.yaml"
TURNAROUND_PATH: Final = CONFIGS / "turnaround.yaml"
ACTION_TURNAROUND: Final[Mapping[str, int]] = MappingProxyType(
    {"ask_history": 5, "examine": 10, "bedside_test": 15, "consultant_session": 240}
)
ESTIMATE: Final = "estimate"


class TablesError(ValueError):
    """The tables are missing or malformed."""


@dataclass(frozen=True)
class Price:
    inr: int
    source: str

    @property
    def estimated(self) -> bool:
        return self.source == ESTIMATE


@dataclass(frozen=True)
class Tables:
    prices: dict[str, Price]
    minutes: dict[str, int]  # turnaround by item id or action
    unmatched_price: int
    unmatched_turnaround: int

    def price(self, item_id: str | None) -> Price:
        found = self.prices.get(item_id or "")
        return found or Price(inr=self.unmatched_price, source=ESTIMATE)

    def turnaround(self, key: str | None) -> int:
        return self.minutes.get(key or "", self.unmatched_turnaround)


def generate_tables(catalogue: Catalogue) -> Tables:
    tests = [i for i in catalogue.items if i.kind == "test"]
    prices = {
        t.id: Price(inr=t.price_inr, source=t.price_source or ESTIMATE)
        for t in tests
        if t.price_inr is not None
    }
    turnaround = {t.id: t.tat_minutes for t in tests if t.tat_minutes is not None}
    return Tables(
        prices=dict(sorted(prices.items())),
        minutes={**ACTION_TURNAROUND, **dict(sorted(turnaround.items()))},
        unmatched_price=int(statistics.median(p.inr for p in prices.values())),
        unmatched_turnaround=int(statistics.median(turnaround.values())),
    )


def _header(what: str) -> str:
    digest = hashlib.sha256((DEFAULT_CATALOGUE_DIR / "tests.csv").read_bytes()).hexdigest()
    return (
        f"# {what}, generated by `sambhasha tables generate` from catalogue"
        f" v{PINNED_CATALOGUE_VERSION}\n"
        f"# (case-library/catalogue/tests.csv, SHA-256 {digest[:16]}). Do not edit by hand.\n"
    )


def render_tables(tables: Tables) -> tuple[str, str]:
    """The two YAML files' text, deterministic for the same catalogue."""
    prices = {
        "unmatched": {"inr": tables.unmatched_price, "source": ESTIMATE},
        "items": {k: {"inr": p.inr, "source": p.source} for k, p in tables.prices.items()},
    }
    turnaround = {
        "unmatched": tables.unmatched_turnaround,
        "minutes": dict(tables.minutes),
    }
    dump = {"sort_keys": False, "allow_unicode": True, "width": 200}
    return (
        _header("Prices in INR") + yaml.safe_dump(prices, **dump),  # type: ignore[call-overload]
        _header("Turnaround times in minutes") + yaml.safe_dump(turnaround, **dump),  # type: ignore[call-overload]
    )


def write_tables(tables: Tables) -> tuple[Path, Path]:
    prices, turnaround = render_tables(tables)
    PRICES_PATH.write_text(prices, encoding="utf-8")
    TURNAROUND_PATH.write_text(turnaround, encoding="utf-8")
    return PRICES_PATH, TURNAROUND_PATH


def load_tables(prices_path: Path = PRICES_PATH, turnaround_path: Path = TURNAROUND_PATH) -> Tables:
    try:
        prices = yaml.safe_load(prices_path.read_text(encoding="utf-8"))
        turnaround = yaml.safe_load(turnaround_path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise TablesError(
            f"{error.filename} is missing: run `uv run sambhasha tables generate`"
        ) from error
    try:
        return Tables(
            prices={
                k: Price(inr=int(v["inr"]), source=str(v["source"]))
                for k, v in prices["items"].items()
            },
            minutes={k: int(v) for k, v in turnaround["minutes"].items()},
            unmatched_price=int(prices["unmatched"]["inr"]),
            unmatched_turnaround=int(turnaround["unmatched"]),
        )
    except (KeyError, TypeError, ValueError) as error:
        raise TablesError(f"malformed tables: {error}; regenerate them") from error
